### ISSUE TITLE
[Bug]: container test_allocator should be skipped if testing is disabled

### ISSUE THREAD

**Issue by here-abarany** [abseil/abseil-cpp#1717] opened 2024-07-16 18:05 UTC
### Describe the issue

If testing is disabled, I would expect all dependencies on googletest to be removed. However, the internal `test_allocator` target inside of the container directory still gets created, which expects the `GTest::gmock` target to exist. As a result, if googletest isn't available, a CMake error will be raised due to the gmock target not existing.

### Steps to reproduce the problem

Run CMake with testing disabled on a system without googletest installed.

### What version of Abseil are you using?

20240116 (as part of protobuf)

### What operating system and version are you using?

Windows 10

### What compiler and version are you using?

Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33812 for x86

### What build system are you using?

cmake version 3.30.0

**Comment by aiusepsi** [comment] 2024-07-17 09:40
I'm seeing the same thing. I suspect that a change in a recent version of cmake (possibly 3.30.0) as identical code built with earlier versions of CMake isn't failing.

It seems that the problem is fixed in the main branch, c.f. these issues:
https://github.com/open-telemetry/opentelemetry-cpp/issues/2998
https://github.com/abseil/abseil-cpp/pull/1536

Alternatively, commenting out line 215 "GTest::gmock" in absl/container/CMakeLists.txt works.

**Comment by jschueller** [comment] 2024-07-18 14:06
see #1536

**Comment by k0T0z** [comment] 2024-08-03 14:41
> Alternatively, commenting out line 215 "GTest::gmock" in absl/container/CMakeLists.txt works.

Thanks

**Comment by derekmauro** [comment] 2024-09-16 13:12
It looks like this has been fixed.

**Closed as completed by derekmauro** 2024-09-16 13:12 UTC
