### ISSUE TITLE
no items defined to be installed

### ISSUE THREAD

**Issue by darix** [abseil/abseil-cpp#155] opened 2018-08-07 22:14 UTC
which ends a build for my rpm package with:

     make: *** No rule to make target 'install'.  Stop.

Please advice which targets should be installed where. Thank you in advance

**Comment by darix** [comment] 2018-08-07 22:15
as a small addition: 

definition so versions for all the shared libraries that are being build would be awesome

**Comment by derekmauro** [comment] 2018-08-08 13:48
This is probably a duplicate of https://github.com/abseil/abseil-cpp/issues/111, but I'll let @JonathanDCohen, who is working on cmake support, and @mbxx who is working on the LTS release comment. It seems like solving this should have been a prerequisite for the LTS release.

**Comment by mbxx** [comment] 2018-08-10 14:47
I'm afraid I don't understand what being requested here, probably because I haven't worked on cmake which I'm inferring this has something to do with, but I'm happy to comment on the LTS branch.

Abseil is looking into adding support for shared libraries, but that's not something our code was designed for, so we don't officially support it yet.  The most likely outcome is we'll support building shared libraries from the LTS branches as long as those libraries are loaded once and not unloaded.  In this case, we'd add .so build targets to future LTS branches (but not to Abseil at head).

**Comment by JonathanDCohen** [comment] 2018-08-10 16:13
It seems like the initial comment was cut off at the beginning.  Installation support hasn't been added yet, but it will come soon.

**Comment by darix** [comment] 2018-08-10 16:58
Even if you dont have shared libraries yet: things that could be installed 

headers and needed source files to /usr/include/abseil-cpp

maybe a cmake finder installed into /usr/share/cmake. 

pkgconfig files might also be good. for support finding with non cmake build systems.

**Comment by OlafvdSpek** [comment] 2018-11-20 13:04
Hi darix

> headers and needed source files to `/usr/include/abseil-cpp`

Shouldn't it be `/usr/include/absl`?

**Comment by darix** [comment] 2018-11-20 14:59
I have no preference regarding the path. I will just query it via the pkg-config file and be done with it.

**Comment by LebedevRI** [comment] 2018-11-20 16:18
It is generally a good idea to put them so that they are **NOT** picked by default unless you actually specify their path via `-I`/`-isystem`.

**Comment by OlafvdSpek** [comment] 2018-11-20 17:05
@LebedevRI Why?

I think cmake has defaults for this.

**Comment by LebedevRI** [comment] 2018-11-20 17:10
Same reason why some buildsystems have airgapped mode, with all the explicitly specified dependencies being copied into special 'chroot' to ensure that all the deps are explicitly specified,
and nothing not specified is not being used. (the strictness may wary)

**Comment by OlafvdSpek** [comment] 2018-11-20 17:12
If you don't want the standard include path, specify another include path...
Installing stuff in non-standard locations doesn't seem like the right approach.

**Comment by JonathanDCohen** [comment] 2019-02-26 23:27
Circling back after a while, https://github.com/abseil/abseil-hello has the supported way to use abseil with cmake.  This is also a duplicate of #111, so I will close it and direct everyone there.

**Closed as completed by JonathanDCohen** 2019-02-26 23:27 UTC
Labels: duplicate, enhancement, cmake
