### ISSUE TITLE
20211102.0 build fails with `ABSL_USE_EXTERNAL_GOOGLETEST=ON`

### ISSUE THREAD

**Issue by kloczek** [abseil/abseil-cpp#1102] opened 2022-01-26 16:10 UTC
**Describe the bug**
Looks lik esometing is still missing when `abseil-cpp` is build wqith external gtest

```console
+ /usr/bin/cmake -B x86_64-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S . -D ABSL_USE_EXTERNAL_GOOGLETEST=ON -D BUILD_TESTING=ON
-- The CXX compiler identification is GNU 12.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:74 (message):
  A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake
  3.8 and up.  We recommend enabling this option to ensure your project still
  builds correctly.


-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found GTest: /usr/lib64/cmake/GTest/GTestConfig.cmake (found version "1.11.0")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
```
And build fails with:
```
[ 31%] Building CXX object absl/container/CMakeFiles/absl_btree_test.dir/btree_test.cc.o
cd /home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/x86_64-redhat-linux-gnu/absl/container && /usr/bin/g++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -I/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -Wall -Wextra -Wcast-qual -Wconversion-null -Wformat-security -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -DNOMINMAX -Wno-conversion-null -Wno-deprecated-declarations -Wno-missing-declarations -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-private-field -MD -MT absl/container/CMakeFiles/absl_btree_test.dir/btree_test.cc.o -MF CMakeFiles/absl_btree_test.dir/btree_test.cc.o.d -o CMakeFiles/absl_btree_test.dir/btree_test.cc.o -c /home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In function ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest()’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:22: error: ‘random_seed’ was not declared in this scope; did you mean ‘random_r’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                      ^~~~~~~~~~~
      |                      random_r
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:7: error: there are no arguments to ‘GTEST_FLAG_GET’ that depend on a template parameter, so a declaration of ‘GTEST_FLAG_GET’ must be available [-fpermissive]
  598 |       GTEST_FLAG_GET(random_seed));
      |       ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:7: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In function ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest()’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:22: error: ‘random_seed’ was not declared in this scope; did you mean ‘random_r’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                      ^~~~~~~~~~~
      |                      random_r
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:7: error: there are no arguments to ‘GTEST_FLAG_GET’ that depend on a template parameter, so a declaration of ‘GTEST_FLAG_GET’ must be available [-fpermissive]
  622 |       GTEST_FLAG_GET(random_seed));
      |       ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_set<int>; C = std::set<int, std::less<int>, std::allocator<int> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:797:35:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::SetTest() [with K = int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:815:42:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_set<long int>; C = std::set<long int, std::less<long int>, std::allocator<long int> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:797:35:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::SetTest() [with K = long int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:816:42:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_set<std::__cxx11::basic_string<char> >; C = std::set<std::__cxx11::basic_string<char> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:797:35:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::SetTest() [with K = std::__cxx11::basic_string<char>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:817:47:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_set<absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<absl::lts_20211102::Cord> >; C = std::set<absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<absl::lts_20211102::Cord> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:797:35:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::SetTest() [with K = absl::lts_20211102::Cord; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:818:44:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_set<std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<int, int> > >; C = std::set<std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<int, int> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:797:35:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::SetTest() [with K = std::pair<int, int>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:819:53:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_map<int, int>; C = std::map<int, int>]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:810:38:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MapTest() [with K = int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:820:42:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_map<long int, long int, std::less<long int>, std::allocator<std::pair<const long int, long int> > >; C = std::map<long int, long int, std::less<long int>, std::allocator<std::pair<const long int, long int> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:810:38:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MapTest() [with K = long int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:821:42:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >; C = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:810:38:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MapTest() [with K = std::__cxx11::basic_string<char>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:822:47:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_map<absl::lts_20211102::Cord, absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<std::pair<const absl::lts_20211102::Cord, absl::lts_20211102::Cord> > >; C = std::map<absl::lts_20211102::Cord, absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<std::pair<const absl::lts_20211102::Cord, absl::lts_20211102::Cord> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:810:38:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MapTest() [with K = absl::lts_20211102::Cord; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:823:44:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeTest() [with T = absl::lts_20211102::btree_map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >; C = std::map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:810:38:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MapTest() [with K = std::pair<int, int>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:824:53:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:598:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  598 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multiset<int>; C = std::multiset<int, std::less<int>, std::allocator<int> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:834:46:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiSetTest() [with K = int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:852:52:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multiset<long int, std::less<long int>, std::allocator<long int> >; C = std::multiset<long int, std::less<long int>, std::allocator<long int> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:834:46:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiSetTest() [with K = long int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:853:52:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multiset<std::__cxx11::basic_string<char>, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::__cxx11::basic_string<char> > >; C = std::multiset<std::__cxx11::basic_string<char>, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::__cxx11::basic_string<char> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:834:46:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiSetTest() [with K = std::__cxx11::basic_string<char>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:854:57:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multiset<absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<absl::lts_20211102::Cord> >; C = std::multiset<absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<absl::lts_20211102::Cord> >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:834:46:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiSetTest() [with K = absl::lts_20211102::Cord; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:855:54:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multiset<std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<int, int> > >; C = std::multiset<std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<int, int> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:834:46:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiSetTest() [with K = std::pair<int, int>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:856:63:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multimap<int, int>; C = std::multimap<int, int, std::less<int>, std::allocator<std::pair<const int, int> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:847:49:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiMapTest() [with K = int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:857:52:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multimap<long int, long int, std::less<long int>, std::allocator<std::pair<const long int, long int> > >; C = std::multimap<long int, long int, std::less<long int>, std::allocator<std::pair<const long int, long int> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:847:49:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiMapTest() [with K = long int; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:858:52:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multimap<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >; C = std::multimap<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:847:49:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiMapTest() [with K = std::__cxx11::basic_string<char>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:859:57:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multimap<absl::lts_20211102::Cord, absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<std::pair<const absl::lts_20211102::Cord, absl::lts_20211102::Cord> > >; C = std::multimap<absl::lts_20211102::Cord, absl::lts_20211102::Cord, std::less<absl::lts_20211102::Cord>, std::allocator<std::pair<const absl::lts_20211102::Cord, absl::lts_20211102::Cord> > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:847:49:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiMapTest() [with K = absl::lts_20211102::Cord; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:860:54:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc: In instantiation of ‘void absl::lts_20211102::container_internal::{anonymous}::BtreeMultiTest() [with T = absl::lts_20211102::btree_multimap<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >; C = std::multimap<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >]’:
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:847:49:   required from ‘void absl::lts_20211102::container_internal::{anonymous}::MultiMapTest() [with K = std::pair<int, int>; int N = 256]’
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:861:63:   required from here
/home/tkloczko/rpmbuild/BUILD/abseil-cpp-20211102.0/absl/container/btree_test.cc:622:33: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  622 |       GTEST_FLAG_GET(random_seed));
      |                                 ^
      |                                 GTEST_FLAG
At global scope:
```

**Comment by derekmauro** [comment] 2022-01-26 16:25
Duplicate of #1063. Basically Abseil is using features of GoogleTest that are not in a "released" version of GoogleTest.

**Closed as completed by derekmauro** 2022-01-26 16:25 UTC
Labels: bug

**Comment by kloczek** [comment] 2022-01-26 17:23
What is the sense to make a release of the code agaist unre4leased other library? 🤔

**Comment by derekmauro** [comment] 2022-01-26 19:35
We generally work at head and only provide releases because others expect them, so this wasn't something we considered. In the future we will do a coordinated release to prevent this issue.
