### ISSUE TITLE
CUSTOMBUILD : error : downloading 'https://github.com/google/googletest/archive/master.zip' failed

### ISSUE THREAD

**Issue by QuellaZhang** [abseil/abseil-cpp#1060] opened 2021-11-16 10:57 UTC
Hello,

We build abseil-cpp on MSVC, and found a new issue today when executing cmake command. Looks like the "https://github.com/google/googletest/archive/master.zip" does not exist.

**Error info:**
 Checking Build System
  Creating directories for 'googletest'
  Performing download step (download, verify and extract) for 'googletest'
  -- Downloading...
     dst='F:/gitP/abseil/abseil-cpp/build_x86/googletest-external/googletest-prefix/src/master.zip'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/google/googletest/archive/master.zip'
  -- [download 100% complete]
  CMake Error at googletest-external/googletest-prefix/src/googletest-stamp/download-googletest.cmake:170 (message):
    Each download failed!
  
CUSTOMBUILD : error : downloading 'https://github.com/google/googletest/archive/master.zip' failed [F:\gitP\abseil\abseil-cpp\build_x86\googletest-external\googletest.vcxproj]
            status_code: 22
            status_string: "HTTP response code said error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 192.30.255.112:443...

**Comment by derekmauro** [comment] 2021-11-16 18:29
Simply replace master.zip with main.zip.

Closing this since you didn't provide reproduction instructions. We can't tell if this is an error on our end, but it may be fixed by #1062.

I also recommend reading https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-live-at-head-and-how-do-i-do-it specifically about why you shouldn't be using master.zip or main.zip directly.

**Closed as completed by derekmauro** 2021-11-16 18:29 UTC
Labels: bug
