### ISSUE TITLE
std::ios::hex not always an enumerated type of fmtflags

### ISSUE THREAD

**Issue by mark65536** [abseil/abseil-cpp#354] opened 2019-07-27 23:57 UTC
When compiling abseil for VxWorks 7, I run into a compilation error about `std::ios::hex` (and `::oct`) not being enumerated types.

The line in question is here: https://github.com/abseil/abseil-cpp/blob/36d37ab992038f52276ca66b9da80c1cf0f57dc2/absl/numeric/int128.cc#L184

While this works on most platforms, it relies on implementation details, specifically that the underlying type for `fmtflags` will be either an int and an enum, and have `std::ios::hex` and `std::ios::oct` as enumerated types. Without disclosing the proprietary VxWorks source code, I can say that they do not implement `fmtflags` the same way, 

Their implementation is still in line with the spec here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf, section 27.5.3.1.2,
> The type fmtflags is a bitmask type (17.5.2.1.3). Setting its elements has the effects indicated in
Table 122.
> Type fmtflags also defines the constants indicated in Table 123.

The simple fix in my case was to wrap this line in `static_cast<int>()`: https://github.com/abseil/abseil-cpp/blob/36d37ab992038f52276ca66b9da80c1cf0f57dc2/absl/numeric/int128.cc#L183

I'm curious if this warrants a pull request, or if you have alternate suggestions for ensuring compatibility.

**Comment by EricWF** [comment] 2019-07-28 04:09
Before continuing I must point out Abseil does not support your compiler or standard library. Wa cannot ensure compatibility. That said, I'm happy to fix conformance issues in abseil. And indeed switching on `std::ios::hex` may be one.

On one hand the standard allows `std::ios:fmtflags` to be a instance of `std::bitset`. And you can't switch on `std::bitset`.
>`[bitmask.types]p1`
> Several types defined in [language.support] through [thread] and [depr] are bitmask types. Each bitmask type can be implemented as an enumerated type that overloads certain operators, as an integer type, or as a bitset.
* http://eel.is/c++draft/bitmask.types#1

However `std::bitset` doesn't meet the requirements laid out in `[bitmask.types]p2`, specifically the bitwise operators do not produce constant expressions. It follows that the provided workaround never produces a constant expression.for conforming `std::bitset` implementations.
* http://eel.is/c++draft/bitmask.types#2 
* http://eel.is/c++draft/bitset#operators

Additionally, the code in question (switching on `std::ios::hex`) works with every compiler on godbolt, I suspect this issue is with your standard library.
* https://godbolt.org/z/7G7E2z

Since we don't support VxWare, can't reproduce the issue, or test and verify the workaround, I'm closing this issue. (Barring further information about the exact nature of the compilation failure).

**Closed as completed by EricWF** 2019-07-28 04:09 UTC
