### ISSUE TITLE
Compatibility with c++20 standard

### ISSUE THREAD

**Issue by okrasniuk** [abseil/abseil-cpp#847] opened 2020-11-19 12:05 UTC
**Describe the bug**

error C2039: 'result_of': is not a member of 'std'
std::result_of is removed in c++20
You are using it in <absl/meta/type_traits.h>
And it is imposible to use absl with c++20 compiler option.

**Steps to reproduce the bug**

just try compile any cpp and include for example:
#include <absl/container/btree_set.h>

**What version of Abseil are you using?**

master

**What operating system and version are you using**

Windows 10 Pro

**What compiler and version are you using?**

cl.exe  version 19.28.29333 for x64

**Comment by derekmauro** [comment] 2020-11-19 14:37
This is a duplicate of #649, which there is a pending fix for. Let me see if I can push that along.

**Closed as completed by derekmauro** 2020-11-19 14:37 UTC
Labels: bug, duplicate
