### ISSUE TITLE
Installs shared libraries without SONAME

### ISSUE THREAD

**Issue by yurivict** [abseil/abseil-cpp#944] opened 2021-04-21 23:20 UTC
**Describe the bug**
The FreeBSD ports framework complains:
```
Error: /usr/local/lib/python3.7/site-packages/ortools/.libs/libortools.so.8 is linked to /usr/local/lib/libabsl_flags.so.2103.0.0 which does not have a SONAME.  devel/abseil needs to be fixed.
Error: /usr/local/lib/python3.7/site-packages/ortools/.libs/libortools.so.8 is linked to /usr/local/lib/libabsl_flags_reflection.so.2103.0.0 which does not have a SONAME.  devel/abseil needs to be fixed.
```

Could you please add SONAME?

Thanks,
Yuri

**Comment by derekmauro** [comment] 2021-04-22 14:12
Duplicate of #862

**Closed as completed by derekmauro** 2021-04-22 14:12 UTC
Labels: bug
