### ISSUE TITLE
Undefined symbol on macOS in dylib

### ISSUE THREAD

**Issue by BotellaA** [abseil/abseil-cpp#624] opened 2020-02-25 21:32 UTC
I got this error while compiling `libabsl_cord.dylib`

```
Undefined symbols for architecture x86_64:
  "absl::numbers_internal::FastIntToBuffer(unsigned long long, char*)", referenced from:
      char* absl::numbers_internal::FastIntToBuffer<unsigned long>(unsigned long, char*) in cord.o
  "absl::StrCat(absl::AlphaNum const&, absl::AlphaNum const&)", referenced from:
      absl::strings_internal::CordTestAccess::LengthToTag(unsigned long) in cord.o
  "absl::StrCat(absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&)", referenced from:
      absl::Cord::RemovePrefix(unsigned long) in cord.o
      absl::Cord::RemoveSuffix(unsigned long) in cord.o
  "absl::CEscape(absl::string_view)", referenced from:
      absl::DumpNode(absl::cord_internal::CordRep*, bool, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in cord.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any idea?

**Comment by asoffer** [comment] 2020-02-28 21:12
Can you provide reproduction instructions? macOS version, Cmake/Bazel invocation, etc?

**Comment by BotellaA** [comment] 2020-02-29 06:48
I am using macOS 10.15 with CMake [configuration](https://github.com/Geode-solutions/OpenGeode/blob/Absl-dll/cmake/ConfigureAbseil.cmake) and [here](https://github.com/Geode-solutions/OpenGeode/runs/469470175?check_suite_focus=true#step:11:3381) is the log.

**Comment by moubctez** [comment] 2020-03-15 21:58
**libabsl_cord.dylib** must be linked against **libabsl_strings.dylib** (not only **libabsl_strings_internal.dylib**)
This patch should fix the problem:
```
--- absl/strings/CMakeLists.txt.orig
+++ absl/strings/CMakeLists.txt
@@ -538,6 +538,7 @@ absl_cc_library(
   COPTS
     ${ABSL_DEFAULT_COPTS}
   DEPS
+    absl::strings
     absl::strings_internal
     absl::base
     absl::base_internal
```

**Comment by KokutoSan** [comment] 2020-04-22 07:53
I have the same problem as @BotellaA regarding the **libabsl_cord.dylib**: 
```
[ 97%] Linking CXX shared library libabsl_cord.dylib
Undefined symbols for architecture x86_64:
  "absl::lts_2020_02_25::numbers_internal::FastIntToBuffer(unsigned long long, char*)", referenced from:
      absl::lts_2020_02_25::Cord::RemovePrefix(unsigned long) in cord.cc.o
      absl::lts_2020_02_25::Cord::RemoveSuffix(unsigned long) in cord.cc.o
      absl::lts_2020_02_25::strings_internal::CordTestAccess::LengthToTag(unsigned long) in cord.cc.o
  "absl::lts_2020_02_25::StrCat(absl::lts_2020_02_25::AlphaNum const&, absl::lts_2020_02_25::AlphaNum const&)", referenced from:
      absl::lts_2020_02_25::strings_internal::CordTestAccess::LengthToTag(unsigned long) in cord.cc.o
  "absl::lts_2020_02_25::StrCat(absl::lts_2020_02_25::AlphaNum const&, absl::lts_2020_02_25::AlphaNum const&, absl::lts_2020_02_25::AlphaNum const&, absl::lts_2020_02_25::AlphaNum const&)", referenced from:
      absl::lts_2020_02_25::Cord::RemovePrefix(unsigned long) in cord.cc.o
      absl::lts_2020_02_25::Cord::RemoveSuffix(unsigned long) in cord.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [absl/strings/libabsl_cord.dylib] Error 1
make[1]: *** [absl/strings/CMakeFiles/cord.dir/all] Error 2
make: *** [all] Error 2
```

I've patched the **absl/stringsCMakeLists.txt** file as described by @moubctez and my compilation of abseil-cpp works as expected:
```
[ 97%] Linking CXX shared library libabsl_cord.dylib
[ 97%] Built target cord
Scanning dependencies of target status
[ 98%] Building CXX object absl/status/CMakeFiles/status.dir/status.cc.o
[ 98%] Building CXX object absl/status/CMakeFiles/status.dir/status_payload_printer.cc.o
[ 99%] Linking CXX shared library libabsl_status.dylib
[ 99%] Built target status
Scanning dependencies of target bad_any_cast_impl
[ 99%] Building CXX object absl/types/CMakeFiles/bad_any_cast_impl.dir/bad_any_cast.cc.o
[100%] Linking CXX shared library libabsl_bad_any_cast_impl.dylib
[100%] Built target bad_any_cast_impl
```

I wonder if it is possible to add this change in the master branch and provide it in the next release.
I can make the PR but as the idea comes from @moubctez I prefer to know if it is OK for him or not.

**Comment by moubctez** [comment] 2020-04-22 08:30
@KokutoSan Please, do the PR. :)

**Comment by KokutoSan** [comment] 2020-04-22 10:02
@moubctez I've made a PR #670 for this and the problem is on its_2020_02_25 branch. So my PR was against lts_2020_02_25 branch but maybe it can be good to have this on the master branch too.

**Comment by derekmauro** [comment] 2020-04-22 14:25
Hi, sorry this issue was ignored. The patch in #670 looks correct to me. I will also apply the fix to the master branch.

**Comment by KokutoSan** [comment] 2020-04-22 19:21
@derekmauro No problem, I can easily understand the fact that it is not possible to process or to keep an eye on all issues. I've the same problem at work ;-) 

Maybe we are not a lot of people to build abseil-cpp as shared library on MacOS.

**Comment by derekmauro** [comment] 2020-04-22 19:50
This should be fixed.

**Closed as completed by derekmauro** 2020-04-22 19:50 UTC
