### ISSUE TITLE
Naming: Base64Escape vs BytesToHexString

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#149] opened 2018-07-30 13:41 UTC
I think base64 is more commonly called encoding, not escaping. 

A more consistent name for `BytesToHexString` would be HexEncode. Note that besides the name the parameter passing also differs.

**Comment by mbxx** [comment] 2018-08-02 17:29
I largely agree with the points raised, but I don't think this change is currently practical to make.

I definitely agree that "base64 encoding" is more standard parlance than "base64 escaping".  The RFC uses "encoding", after all.  "base64 escaping" just happens to be what it's usually called inside of Google, for whatever reason.  `Base64Escape` also probably should return a string instead of using an out parameter, because the escaping functions really ought to all be consistent.

I can see why you'd prefer `BytesToHexString` to be called `HexEncode`.  If `Base64Escape` were renamed `Base64Encode`, then the use of the word "Encode" would be consistent.  I don't feel strongly about this, though, because I find that `BytesToHexString` is a pretty good name.

Unfortunately, I don't think it's practical to make this change because doing so would require refactoring every reference to these functions in Google's 250M line codebase as well as creating an shipping a tool to migrate all of Abseil's open source users from the old names to the new names (https://abseil.io/about/compatibility).  The latter is particularly challenging because it would be the first such tool we'd be publishing.  We'd love to get our tooling to the point where changes like this are simple to make, but we're just not there yet.

I'm going to close this issue, but thank you for the good suggestions.  Please keep them coming.

**Closed as completed by mbxx** 2018-08-02 17:29 UTC

**Comment by OlafvdSpek** [comment] 2018-08-02 17:43
Introducing new names and deprecating (doc-only maybe) the old ones is not an option? ;)

> Base64Escape also probably should return a string instead of using an out parameter, because the escaping functions really ought to all be consistent.

I'm not sure, you'd no longer be able to re-use pre-existing string storage.

**Comment by mbxx** [comment] 2018-08-02 22:29
> Introducing new names and deprecating (doc-only maybe) the old ones is not an option? ;)

It's really not.  (I'm not sure how to interpret the winking emoticon, so apologies in advance if I take this too literally.)  I elided some assumptions in my earlier response, let me try to fill those in.  Some of this is likely to seem a bit alien and some of this I haven't been asked to unpack before, so please ask questions about anything that's weird or surprising.

As background, the code that makes up Abseil has been around for over a decade, it's depended on by 250M lines of code, and it is continuously under active development.  We expect it to continue to exist for at least another decade while active development continues and the amount of code that depends on Abseil grows super-linearly.

With that in mind, if new names were to be introduced and the old names deprecated, what's the long-term plan for the old names?

One option is to leave them around forever.  This leads to an unbounded accumulation of technical debt as active development continues on Abseil over the years.  These specific names are relatively benign, but in aggregate this approach isn't sustainable.

Another option is to pick a date for the deprecated functions to go away and simply delete them on that date.  This seems like it would probably be pretty reasonable if Abseil put out versioned releases and users were responsible for upgrading themselves from one version to the next, but Abseil takes a live-at-head approach to development, and in particular, it's a part of Google's monorepo.  Users don't choose which version of Abseil they build with, they always build with the latest version.  Deleting the deprecated functions will immediately break any callers that haven't updated themselves.  There are a few choices here, none of which is palatable:
1. Wait until all callers have updated themselves.  In a 250M line monorepo where some of the code isn't actively owned and maintained, this effectively means that deprecated code can never be deleted.
1. Break callers that haven't updated by a certain date.  This isn't tenable as long as there's some code that's too important to break, which is certainly the case at Google.  As soon as there's code that can't be broken, the team responsible for that code is no longer under any obligation to update, so again, the deprecated code cannot be deleted.
1. Somehow obligate callers to update by a certain date.  I don't see how this is possible, but even if it were, the engineers who are obligated to do the updates will rightly complain about how much work they need to do just to keep up with the deprecations.  A logical outcome of this is some kind of a limit to the amount of churn caused by the deprecations, which would slow down the rate at which Abseil development can occur.  That's something we're explicitly trying to avoid.

The final option is for Abseil to do the refactoring necessary to remove the old names.  This is something we're capable of doing, but as I mentioned, it's a lot of work.

> I'm not sure, you'd no longer be able to re-use pre-existing string storage.

I was wondering if someone would mention this :)  I agree that reusing the storage already allocated in a string can be more efficient.  Were I to make this change, I'd try to measure its impact first.  It's certainly more common for the out parameter to be a newly allocated string, but there could be important cases in which the memory is being reused.  If there's no performance difference, I prefer the API of returning a string.  If there is a meaningful performance difference, I might either standardize all of the functions to use an out parameter or I might provide overloads for both returning a string and using an out parameter.  I'm not sure which offhand.
