### ISSUE TITLE
Build with MSVC get warning C4018 (signed/unsigned mismatch)

### ISSUE THREAD

**Issue by 2power10** [abseil/abseil-cpp#156] opened 2018-08-08 08:23 UTC
I generate the abseil-cpp using CMake in Windows, and I got some warnings C4018 which block the building.

I used following command to generate VS solution:

```
C:/Code/google/abseil-cpp/build>cmake ../
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.14.26433.0
-- The CXX compiler identification is MSVC 19.14.26433.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Code/google/abseil-cpp/build
```

The warnings I got:

```
abseil-cpp\absl\strings\internal\charconv_parse.cc(372): warning C4018: '>=': signed/unsigned mismatch
abseil-cpp\absl\strings\internal\charconv_parse.cc(375): warning C4018: '>': signed/unsigned mismatch
abseil-cpp\absl\strings\internal\charconv_parse.cc(395): warning C4018: '>=': signed/unsigned mismatch
abseil-cpp\absl\strings\internal\charconv_parse.cc(409): warning C4018: '>=': signed/unsigned mismatch
abseil-cpp\absl\strings\internal\charconv_parse.cc(412): warning C4018: '>': signed/unsigned mismatch
abseil-cpp\absl\strings\internal\str_format\bind.cc(212): warning C4018: '>': signed/unsigned mismatch
```

**Comment by derekmauro** [comment] 2018-08-08 14:01
Duplicate of https://github.com/abseil/abseil-cpp/pull/153 (and possibly https://github.com/abseil/abseil-cpp/issues/40 as well).

**Closed as completed by derekmauro** 2018-08-08 14:01 UTC
Labels: duplicate
