### ISSUE TITLE
std::result_of is depreciated, code doesn't compile on MSVC

### ISSUE THREAD

**Issue by TrianglesPCT** [abseil/abseil-cpp#759] opened 2020-08-07 18:29 UTC
This line in type_traits.h

```
template <typename T>
using result_of_t = typename std::result_of<T>::type;
```

Does not compile on MSVC because std::result_of was removed

I think you are supposed to use std::invoke_result, but switching to it just results in other compilation issues

**Comment by derekmauro** [comment] 2020-08-07 20:06
This is a duplicate of #649, and the discussion includes a workaround. See also #705 as well.

**Closed as completed by derekmauro** 2020-08-07 20:06 UTC
Labels: duplicate
