### ISSUE TITLE
MacOS build failure: illegal thread local variable

### ISSUE THREAD

**Issue by devjgm** [abseil/abseil-cpp#965] opened 2021-05-25 19:58 UTC
I'm trying to upgrade `google-cloud-cpp` (https://github.com/googleapis/google-cloud-cpp/pull/6628) to use the latest Abseil release, and our build breaks on MacOS. The following is a minimal repro that shows the error.

**Repro**
```
$ curl -sSL https://github.com/abseil/abseil-cpp/archive/refs/tags/20210324.1.tar.gz | tar zxvf - 
$ cd abseil-cpp-20210324.1/ 
$ bazel build ...
Starting local Bazel server and connecting to it...
INFO: Analyzed 366 targets (49 packages loaded, 2171 targets configured).
INFO: Found 366 targets...
INFO: From Linking absl/flags/libflag.a:
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: bazel-out/darwin-fastbuild/bin/absl/flags/libflag.a the table of contents is empty (no object file members in the library define global symbols)
ERROR: /Users/jgm/abseil-cpp-20210324.1/absl/synchronization/BUILD.bazel:68:11: Linking absl/synchronization/libsynchronization.so failed: (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/absl/synchronization/libsynchronization.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: illegal thread local variable reference to regular symbol __ZN4absl12lts_2021032413base_internal19thread_identity_ptrE for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 20525 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
INFO: Elapsed time: 50.831s, Critical Path: 16.74s
INFO: 470 processes: 209 internal, 261 darwin-sandbox.
```

**Machine info***
```
$ bazel version
Build label: 4.1.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800

$ sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
```

**Comment by derekmauro** [comment] 2021-05-25 20:04
Is this yet another instance of https://github.com/abseil/abseil-cpp/issues/848, which I thought was supposedly fixed with Bazel 4.1.0? Does it work if you pass `--features=-supports_dynamic_linker` to `bazel`?

**Comment by devjgm** [comment] 2021-05-25 20:20
It looks like it. Yes, passing `--features=-supports_dynamic_linker` lets the build pass. Thanks!

Is that the official workaround that customers should use?

**Comment by derekmauro** [comment] 2021-05-25 20:35
I'm actually thinking I may have another workaround for both this issue and https://github.com/abseil/abseil-cpp/issues/954, which may be the same issue. This has been reported enough times that I'm thinking we might just want to try a code fix.

Does https://github.com/derekmauro/abseil-cpp/commit/2da3ef0d639481b638da2d626c7ea75984e85f05 fix the issue for you? I can't reproduce the problem myself.

**Comment by devjgm** [comment] 2021-05-25 20:41
Yep, that fixes the issue on my test Mac.

```
$ curl -sSL https://github.com/derekmauro/abseil-cpp/commit/2da3ef0d639481b638da2d626c7ea75984e85f05.diff | patch -p1
$ bazel build ...
INFO: Analyzed 366 targets (0 packages loaded, 0 targets configured).
INFO: Found 366 targets...
INFO: Elapsed time: 15.628s, Critical Path: 14.22s
INFO: 22 processes: 2 internal, 20 darwin-sandbox.
INFO: Build completed successfully, 22 total actions
```

**Comment by derekmauro** [comment] 2021-05-25 20:50
Great, I'm going to work on getting that submitted. Then I'll do an LTS patch for this issue and one other.

**Closed as completed** 2021-05-27 18:35 UTC
Labels: question

**Comment by derekmauro** [comment] 2021-06-01 14:58
This fix for this issue as been backported to the latest LTS release: https://github.com/abseil/abseil-cpp/releases/tag/20210324.2.
