### ISSUE TITLE
Installs shared libraries without SONAME

### ISSUE THREAD

**Issue by yurivict** [abseil/abseil-cpp#876] opened 2020-12-30 04:13 UTC
**Describe the bug**

The FreeBSD ports framework complains:
```
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/python3.7/site-packages/ortools/.libs/libortools.so.8 is linked to /usr/local/lib/libabsl_flags_parse.so which does not have a SONAME.  devel/abseil needs to be fixed.
```

abseil-20200923.2 is installed.

**Comment by derekmauro** [comment] 2020-12-30 15:05
Duplicate of #862

**Closed as completed by derekmauro** 2020-12-30 15:05 UTC
Labels: bug
