### ISSUE TITLE
Error when cross compile grpc with abseil-cpp

### ISSUE THREAD

**Issue by avalon1610** [abseil/abseil-cpp#635] opened 2020-03-10 05:40 UTC
when I try to cross compile grpc use arm-linux-gnueabihf-5.2.1-g++, it failed with
```
Linking CXX executable check_epollexclusive 
/usr/lib/librt.so: error adding symbols: File in wrong format
```
/use/lib/librt.so is a host platform lib obviously. 
I investigated dependencies for grpc, found this line 
```
find_library(LIBRT rt)
```
in `absl/base/CMakeLists.txt`. 

delete this line, everything will be fine.

so maybe cmake find_library got wrong librt path when cross compile. or something compile arguments went wrong.
(BTW, I set CMAKE_SYSTEM_PROCESSOR to `armv7`  manually because cmake can not detect it  correctly)

**Comment by derekmauro** [comment] 2020-03-11 13:26
Can you provide full reproduction instructions?

**Comment by avalon1610** [comment] 2020-03-12 07:32
I followed the guide in [https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_raspberry_pi.sh](https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_raspberry_pi.sh). 
only replaced the compiler with arm-linux-gnueabihf-5.2.1-g++, which from linaro.

**Comment by derekmauro** [comment] 2020-03-12 21:30
I haven't tried this myself, but I inspected the repo and librt appears to exist on the target platform: https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/arm-linux-gnueabihf/sysroot/lib

I would suggest filing an issue with gRPC and asking the author of that script to look into the problem. I think most of us that work on Abseil are unfamiliar with CMake cross-compiling and no one is going to have the time figure out what is going wrong. The author of that script is probably in the best position to debug the problem.

**Comment by rogeeff** [comment] 2020-04-06 20:06
Please advise us if there is anything  we should be doing in Abseil after you have a discussion with grpc. I'll close this for now, since there is no action item for us at the moment.

**Closed as completed by rogeeff** 2020-04-06 20:06 UTC

**Comment by rizsotto** [comment] 2020-04-15 02:31
I also have an issue with this CMake line. :smile: 

My case is documented in this ticket on the grpc project. grpc/grpc#22646

It looks like that `find_library(LIBRT rt)` will always add `/usr/lib/librt.so` to the linker flags. The `-lrt` would more desirable and would solve the static linking and the cross compilation problem. What do you guys think?
