### ISSUE TITLE
absl::InlinedVector doesn't support move constructors which throw

### ISSUE THREAD

**Issue by jorgbrown** [abseil/abseil-cpp#14] opened 2017-09-28 04:04 UTC
std::vector, when resizing, will only use move if it is declared nothrow.

absl's InlinedVector uses move operations for resizing, regardless.

This means that if a resize operation calls the move constructor and it throws, we end up with a situation where the vector is only partially moved to its new location.  Moving the data back might also throw, and we end up with an inconsistent InlinedVector.

InlinedVector should either use copy constructors in that case, or insist that the move operator is declared nothrow.

**Comment by jorgbrown** [comment] 2017-09-28 04:10
User reported test case at http://codepad.org/YbVsjMy5 but it seems to be inaccessible now.

**Comment by JonathanDCohen** [comment] 2017-09-28 21:39
On a slightly pedantic note, an InlinedVector of objects in maybe-moved-from states is still in a valid state, so this *technically* satisfies basic exception safety -- but I agree it's not a nice thing to do.

I think this is a two step solution -- we declare that InlinedVector only supports T with nothrow move operators in the short term.

In the long term, Abseil's stance on throwing moves constructors is essentially that move constructors can only throw if the allocator can throw -- we're stricter than the standard on thsi point of view.  So as I ramp up the exception-safety test suite we can advise the move constructor to be noexcept if the allocator is noexcept and use the current algorithm, and fall back to copying only if the allocator throws *and* T has a throwing move constructor.

Does this sound reasonable?

**Comment by JonathanDCohen** [comment] 2017-10-17 18:41
Closing as a duplicate of #37

**Closed as completed by JonathanDCohen** 2017-10-17 18:41 UTC
Labels: duplicate
