### ISSUE TITLE
statically linked binary (by bazel) with abseil dependency segfaults on initialization

### ISSUE THREAD

**Issue by pompon0** [abseil/abseil-cpp#571] opened 2019-12-17 10:25 UTC
I'm trying to create a statically linked c++ binary which uses absl/flags.
I'm using bazel for build automation.
Building goes fine, but when executing the binary I get a segfault (it works fine with dynamic linking). I've determined that I can remove all of my code, except for the ParseCommandLine statement, and I still get the segfault.

Minimal example:
https://github.com/pompon0/abseil-segfault

`bazel version`

`Build label: 1.2.1`
`Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar`
`Build time: Tue Nov 26 15:25:10 2019 (1574781910)`
`Build timestamp: 1574781910`
`Build timestamp as int: 1574781910`

**Comment by asoffer** [comment] 2019-12-23 19:10
This sounds a lot like an ABI compatibility issue. Is the statically linked standard library built with the same flags as your target and the Abseil build?

**Comment by pompon0** [comment] 2019-12-23 19:28
The standard library I link statically comes with the operating system, I have no idea what flags it has been compiled with. I doubt however that this is an ABI issue, because when I add more abseil libraries to the binary, it stops segfaulting. Have you tried to reproduce the issue with the example I've provided?

**Comment by asoffer** [comment] 2019-12-30 18:02
Yes, I can reproduce your issue. Do you have another library that, when added stops the segfaulting?

**Comment by pompon0** [comment] 2020-01-03 09:31
I've submitted another example, this one doesn't segfault (on a branch called "ok"):
https://github.com/pompon0/abseil-segfault/tree/ok
Whether it segfaults seems to depend on which features of the library I use (perhaps linker is removing some stuff when it is "unused"). You can try to delete some code and see when it stops working.

**Comment by asoffer** [comment] 2020-01-16 16:52
I've looked into this a bit more but have been unable to find any leads within Abseil's code or build setup. https://github.com/bazelbuild/bazel/issues/1920 may provide some insight, but I think this is something that Bazel does not yet support.

**Comment by asoffer** [comment] 2020-03-14 03:42
Closing, as this seems to be an ongoing Bazel issue. Please reopen if this turns out to be Abseil specific.

**Closed as completed by asoffer** 2020-03-14 03:42 UTC
