### ISSUE TITLE
20200923.2 fails to build on Windows using Clang10 in C++20 mode: no type named 'result_of' in namespace 'std'

### ISSUE THREAD

**Issue by 0x8000-0000** [abseil/abseil-cpp#835] opened 2020-11-02 21:45 UTC
**Describe the bug**

20200923.2 fails to build on Windows using Clang10 in C++20 mode: no type named 'result_of' in namespace 'std'.
std::result_of has been deprecated in C++17 and removed in C++20.

**Steps to reproduce the bug**

(I'm building the Conan package, but I suppose the same problem can be found with a simple test case.)

**What version of Abseil are you using?**

20200923.2

**What operating system and version are you using**

Windows 10

**What compiler and version are you using?**

clang version 10.0.0
Target: x86_64-pc-windows-msvc

**What build system are you using?**

cmake 3.18.3

**Comment by derekmauro** [comment] 2020-11-02 21:50
Duplicate of #649

**Closed as completed by derekmauro** 2020-11-02 21:50 UTC
Labels: bug
