### ISSUE TITLE
Undefined symbols on macOS with -DBUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by essandess** [abseil/abseil-cpp#816] opened 2020-10-13 21:43 UTC
**Describe the bug**

I'm trying to write a MacPorts port of `abseil` with a `cmake` build that includes shared libraries.

When I pass `-DBUILD_SHARED_LIBS` to `cmake`, I hit this error:
```
:info:build /usr/bin/clang++ -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -o libabsl_statusor.dylib -install_name /opt/local/lib/libabsl_statusor.dylib CMakeFiles/statusor.dir/statusor.cc.o  -Wl,-rpath,/opt/local/lib ../strings/libabsl_strings.dylib ../strings/libabsl_strings_internal.dylib ../base/libabsl_base.dylib ../base/libabsl_spinlock_wait.dylib ../numeric/libabsl_int128.dylib ../base/libabsl_throw_delegate.dylib ../types/libabsl_bad_variant_access.dylib ../base/libabsl_raw_logging_internal.dylib ../base/libabsl_log_severity.dylib
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_ports_devel_abseil/abseil/work/abseil-abseil-cpp-bd0de71/build'
:info:build [ 68%] Built target random_distributions
:info:build Undefined symbols for architecture x86_64:
:info:build   "absl::lts_2020_09_23::InternalError(absl::lts_2020_09_23::string_view)", referenced from:
:info:build       absl::lts_2020_09_23::internal_statusor::Helper::HandleInvalidStatusCtorArg(absl::lts_2020_09_23::Status*) in statusor.cc.o
:info:build   "absl::lts_2020_09_23::Status::UnrefNonInlined(unsigned long)", referenced from:
:info:build       absl::lts_2020_09_23::BadStatusOrAccess::~BadStatusOrAccess() in statusor.cc.o
:info:build       absl::lts_2020_09_23::internal_statusor::Helper::HandleInvalidStatusCtorArg(absl::lts_2020_09_23::Status*) in statusor.cc.o
:info:build   "absl::lts_2020_09_23::Status::ToStringSlow() const", referenced from:
:info:build       absl::lts_2020_09_23::internal_statusor::Helper::Crash(absl::lts_2020_09_23::Status const&) in statusor.cc.o
:info:build ld: symbol(s) not found for architecture x86_64
```

**Steps to reproduce the bug**

```
cd abseil-cpp-20200923.1
mkdir build
cd build
/opt/local/bin/cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_STANDARD=11 ..
/usr/bin/make -j12 -w all
```

**What version of Abseil are you using?**

Release 20200923.1

**What operating system and version are you using**

macOS 10.15.7

**What compiler and version are you using?**

```
clang -v
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What build system are you using?**

cmake version 3.18.4

**Comment by essandess** [comment] 2020-10-14 12:19
This issue is also observed when building `grpc`:
* https://github.com/grpc/grpc/issues/24412

**Comment by derekmauro** [comment] 2020-10-14 15:45
Thanks for the report. I'm doing to close this as a duplicate of #817. It should be fixed shortly.

**Closed as completed by derekmauro** 2020-10-14 15:45 UTC
Labels: bug, duplicate
