### ISSUE TITLE
ABSL_FALLTHROUGH_INTENDED should be in a dedicated header

### ISSUE THREAD

**Issue by nico** [abseil/abseil-cpp#90] opened 2018-02-08 00:48 UTC
When clang suggests adding [[clang::fallthrough]], it checks if it knows of a macro expanding to that and if so, suggests inserting that. Chrome has its own FALLTHROUGH macro, but chrome's deps might soon depend on absl, so if ABSL_FALLTHROUGH_INTENDED gets pulled in globally, clang will suggest that instead of the FALLTHROUGH specific to chrome.

The dedicated header should advise to not include the header in libraries's public headers, or if it has to be included, to undefine it again at the end of the header.

See also https://boringssl-review.googlesource.com/c/boringssl/+/25464 and the "It is important..." paragraph in comment 0 on https://bugs.chromium.org/p/chromium/issues/detail?id=807632

**Comment by zhangxy988** [comment] 2018-02-09 16:30
ABSL_FALLTHROUGH_INTENDED is already a public interface of Abseil, not an internal implementation detail. And it would be hard to move a public interface to internal.
I'd like to understand this issue better too. If chrome depends on absl, chrome no longer need FALLTHROUGH because it already has ABSL_FALLTHROUGH_INTENDED. So what is the problem of "clang suggesting ABSL_FALLTHROUGH_INTENDED" if chrome's will depend on absl?
Also I am not sure how moving this to an internal header could solve this problem. Particularly how do we make sure this macro doesn't leak? undefing it at the end of each file that uses it seems like a hard thing to enforce.

**Comment by nico** [comment] 2018-02-22 14:16
It's possible that Chrome might not want to use absl but one of chrome's deps starts using it for example. And even if Chrome does start using some of absl, going from FALLTHROUGH to ABSL_FALLTHROUGH_INTENDED looks like a step back.

**Comment by mbxx** [comment] 2018-02-27 23:26
Let me go a little further than @zhangxy988: ABSL_FALLTHROUGH_INTENDED is intentionally part of Abseil's public API.  The purpose of it is to give code that exists both as open source and as Google-internal code a single macro that works in both situations.

@nico, you said that "going from FALLTHROUGH to ABSL_FALLTHROUGH_INTENDED looks like a step back".  Why is that?  Do you object to the spelling, or is there something else?

If I understand the situation correctly, the root cause of this is a Clang diagnostic showing a poor diagnostic message, right?  Have you tried filing a bug against Clang about the diagnostic?  I've found them to be quite responsive in the past.

**Comment by zhangxy988** [comment] 2018-03-28 15:07
I don't think this issue can be addressed on the Abseil side: The problem is that Abseil wants ABSL_FALLTHROUGH_INTENDED to be a public API. If Chrome (transitively) depends on Abseil and has its own FALLTHROUGH macro, Clang has two macros to choose from for its diagnostic message. This will happen to any project (not just Chrome) with any deps (not just Abseil) as long as there are more than one macro that map to [[clang::fallthrough]], e.g. I depend on both Boost and Abseil. I think a proper way to handle this might be changing Clang diagnostic to support a way for code owner to tag particular macros as "preferred" so it can always be suggested by the diagnostic.

Closing this for now. Feel free to reopen if there is anything else I missed.

**Closed as completed by zhangxy988** 2018-03-28 15:07 UTC
