### ISSUE TITLE
VS 2017 Data Truncation Warning/Error

### ISSUE THREAD

**Issue by scottnice** [abseil/abseil-cpp#66] opened 2017-12-21 16:03 UTC
I understand there is another issue/PR relating to VS 2017 flags and Cmake builds because VS 2017 doesn't recognize the -std=c++11 compiler flag. 

- abseil-cpp\absl\synchronization\internal\graphcycles.cc(282): error C2220: warning treated as error - no 'object' file generated
- abseil-cpp\absl\synchronization\internal\graphcycles.cc(282): warning C4309: 'static_cast': truncation of constant value
``` static const uintptr_t kHideMask = static_cast<uintptr_t>(0xF03A5F7BF03A5F7Bll); ```

Currently building abseil into my project with Cmake. I can get around this error by adding /wd4309 to the abseil-cpp\CMakeLists.txt add_compile_options telling the compiler to not treat this warning as an error.

**Comment by zhangxy988** [comment] 2017-12-22 20:21
I wonder why building with bazel + VS2017 doesn't trigger this warning.
Are you compiling for 32-bit system?

**Comment by scottnice** [comment] 2017-12-23 02:22
Yes, I'm targeting x86 (win32).

**Comment by derekmauro** [comment] 2018-05-21 15:02
Closing as duplicate of #126.

**Closed as completed by derekmauro** 2018-05-21 15:02 UTC
Labels: duplicate
