### ISSUE TITLE
[Bug]: absl::string compilation failure due to function called "Mutable" conflicting with reserved keyword "mutable"

### ISSUE THREAD

**Issue by LucienRochery** [abseil/abseil-cpp#1480] opened 2023-06-16 14:21 UTC
### Describe the issue

Including the file `absl/strings/internal/cord_rep_ring.h` results in a long stream of compilation errors stemming from line 432, declaration of `static CordRepRing* Mutable(CordRepRing* rep, size_t extra);`. This has been the case with clang on MacOS and with g++ on Ubuntu. Compilation with -std=c++20. 

The origin of the problem is that both g++ and clang seem to interpret `Mutable` as the keyword `mutable`. 

The solution is to replace `Mutable` with `Mutable_` or anything else that does not conflict with `mutable`. This leads to successfull compilation. A recursive `grep` from the root absl include directory shows this function is never called, so no further subtitutions are needed. 

The full compiler output (here g++) is attached to this issue. 

[compilation_error_absl.txt](https://github.com/abseil/abseil-cpp/files/11771085/compilation_error_absl.txt)

### Steps to reproduce the problem

Ultimately, the error is triggered when including the file `absl/strings/internal/cord_rep_ring.h`. 

The origin of the include in the case of my project was the inclusion of [GiNaC](https://www.ginac.de/). The file that includes `absl/strings/internal/cord_rep_ring.h` is `cln/complex.h` from [the GiNaC-adjacent CLN library](https://www.ginac.de/CLN/). 

### What version of Abseil are you using?

The issue persists in the latest current master branch. . 

### What operating system and version are you using?

Ubuntu 22.04.2
MacOS 13.0.1

### What compiler and version are you using?

clang:
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.1.0
Thread model: posix

g++:
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

### What build system are you using?

cmake version 3.26.3 on MacOS
cmake version 3.22.1 on Ubuntu

**Comment by derekmauro** [comment] 2023-06-16 16:34
> The origin of the problem is that both g++ and clang seem to interpret Mutable as the keyword mutable.

I find this hard to believe. We build with both GCC and Clang and don't see this issue. Are you sure there is nothing in your project that is doing `#define Mutable mutable`?

**Comment by LucienRochery** [comment] 2023-06-16 18:38
Strange indeed. I tried determining if that is the case by grepping in all project files as well as in some of the included headers (ginac.h being the first to trigger the error). This revealed nothing. I then tried simply adding 

    #ifdef Mutable
    printf("Mutable defined!"); 
    exit(1);
    #endif

in main() but the code was not compiled, so the macro must not exist. 

It turns out the keyword "mutable" was a red herring, as I also tried changing the method from `  static CordRepRing* Mutable(CordRepRing* rep, size_t extra);` to `  static CordRepRing* mutable(CordRepRing* rep, size_t extra);` and the compilation errors are not the same. In the latter case, the only error is `error: expected member name or ';' after declaration specifiers`. It also compiles fine if Mutable is replaced by Const, Volatile, Void... so it's not an issue with capitalization due to some compiler option. 

Could the issue be due to some dependency defining a function also named Mutable?

**Comment by derekmauro** [comment] 2023-06-17 02:25
`compilation_error_absl.txt` shows so many errors that I think there must be something wrong with this build. Can you provide a complete minimal example that I can try myself?

**Comment by derekmauro** [comment] 2023-07-31 19:05
Closing because this is not reproducible.

**Closed as not planned by derekmauro** 2023-07-31 19:05 UTC
Labels: can't reproduce
